### ISSUE TITLE
Enabling SSL broke Wazuh app

### ISSUE THREAD

**Issue by hcv-target** [wazuh/wazuh-kibana-app#1809]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.5 | 6.8.2 | 454 |

After successfully enabling TLS for transport and server in kibana, elastic, metricbeat and filebeat, which all work perfectly, launching wazuh-app now returns three errors when opening the app:

Wazuh App: Please set up Wazuh API credentials.
Settings. Error getting API entries
Settings. Error when loading Wazuh setup info

I have followed the guidance in the wazuh docs around setting up TLS and used /var/ossec/api/scripts/configure_api.sh to reset the API configuration. I edited the config.js to match my current environment, as the elastic IP changed from 127.0.0.1 to the external interface.

I've tried every reference in your docs and here on github before reaching out.

Should I try upgrading to 3.10.0 / 6.9.3 and refreshing the app and see if that knocks it loose?

Thanks for an indispensable tool. I'd sleep a lot worse at night without it.

**Comment by adri9valle** [comment]
Hi @hcv-target,

Did you have configured any API entry previously?

Please could you ensure that your API is running properly over TLS executing:

```
$ curl -u <user>:<password> -K https://<manager_ip>:55000
```

> Should I try upgrading to 3.10.0 / 6.9.3 and refreshing the app and see if that knocks it loose?

I always advise upgrading to get the last features of Wazuh, but I think that if you want to upgrade we should fix this problem first.

Waiting for your response

**Comment by hcv-target** [comment]
Hi, @adri9valle , thanks for the quick reply.

API was previously configured and working as expected.

Output from curl:
{"error":0,"data":{"msg":"Welcome to Wazuh HIDS API","api_version":"v3.9.5","hostname":"hcvtarget-web","timestamp":"Thu Sep 19 2019 06:44:40 GMT-0400 (EDT)"}}

Looks like it's working correctly, yet errors persist when launching the wazuh app in kibana.

**Comment by adri9valle** [comment]
Hi @hcv-target,

Did you configure the API which works properly before enabling TLS? If so, maybe the problem is that the **URL** used is still set as `http` instead of `https`.

Could you check that?

Thanks

**Comment by hcv-target** [comment]
It's certainly possible, but I am unable to access the settings in Kibana to check. Is there an alternate method of reading / setting it?

**Comment by ips972** [comment]
I have the same problem as @hcv-target where I'm unable to get to the wazuh settings page. its just not responding. just give the "Wazuh App: Please set up Wazuh API credentials."
and "Settings. Error when loading Wazuh setup info" error message..

testing the api -shows all is well. 
curl -u user:pass -k -X GET "https://127.0.0.1:55000/agents?pretty&offset=0&sort=-ip,name"
works fine for me..

regards

**Comment by hcv-target** [comment]
Hi, @ips972, sorry to hear you're having the same problem. Did you first install and run Elastic/Kibana/Wazuh-app without using SSL/TLS, then set up TLS after? That's how I got to this point.

**Comment by hcv-target** [comment]
@adri9valle , can you shed any light? How do we verify/change the API config if we can't access it in Kibana?

Thanks!

**Comment by hcv-target** [comment]
I attempted to set a new API config using the guidance found at [https://documentation.wazuh.com/3.8/installation-guide/installing-wazuh-server/automatic_api.html#automatic-api](url).

This returned the following error:
`{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/.wazuh/wazuh-configuration/1513629884013]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication token for REST request [/.wazuh/wazuh-configuration/1513629884013]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}},"status":401}`

I feel as if I'm flailing about now, trying anything I can find. Some guidance from @adri9valle or others would be most welcome.

Thanks in advance.

**Comment by hcv-target** [comment]
I've also narrowed down logging in Kibana, and on start I'm seeing this, which appears to be related:

> {"type":"log","@timestamp":"2019-09-26T17:01:40Z","tags":["listening","info"],"pid":404,"message":"Server running at https://host.is.obscured:5601"}
{"type":"log","@timestamp":"2019-09-26T17:01:40Z","tags":["\u001b[34mwazuh\u001b[39m","initialize:init","error"],"pid":404,"message":"Authorization Exception"}
{"type":"log","@timestamp":"2019-09-26T17:01:40Z","tags":["\u001b[34mwazuh\u001b[39m","initialize (checkKibanaStatus)","error"],"pid":404,"message":"Authorization Exception"}
{"type":"log","@timestamp":"2019-09-26T17:01:40Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","error"],"pid":404,"message":"Could not check if the index wazuh-monitoring-3.x-2019.09.26 exists due to Authorization Exception"}
{"type":"log","@timestamp":"2019-09-26T17:01:40Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","error"],"pid":404,"message":"Error creating index .wazuh-version."}

**Comment by jsanchez91** [comment]
Hi @hcv-target 

To change the URL of your API configurated:

### First solution:
Try to access directly to Wazuh app settings (this works sometimes):
```
http://<yourhost>:5601/app/wazuh#/settings?_g=() 
```
And edit the values of your current API

### Second solution

Open Kibana and go to `Dev Tools` console.
Get the `_id` of the document you want to change:
```
GET .wazuh/_search
```
You will get an output similar to this:
![image](https://user-images.githubusercontent.com/3064506/65765384-658a1380-e128-11e9-96d3-ba877c0d4b78.png)

I got the `" _id ":" 1569582827137 "`, but you will get another value. In the following request, replace the fields between `<>` with your `_id` and your URL.

```html 
POST .wazuh/_doc/<YOUR_ID>/_update
{
    "script" : {
        "source": "ctx._source.url = params.url",
        "lang": "painless",
        "params" : {
            "url" : "<YOUR_HTTPS_URL>"
        }
    }
}
```
> Remove the symbols <> too

![image](https://user-images.githubusercontent.com/3064506/65767245-96207c00-e12d-11e9-8304-614f9e11462f.png)

If you need to change other value, replace the `url` word in this line:

` "source": "ctx._source.url = params.url",` => ` "source": "ctx._source.<FIELD_NAME> = params.url",`

I hope it helps. Please, don't hesitate to ask again if you have more doubts.
Best regards,

Jose

**Comment by hcv-target** [comment]
Hi, @jsanchez91  and thanks for the reply. My url is already set correctly, as https://my.host.org:5601, and I can connect successfully to the API via command line using the same credentials returned by 

`GET .wazuh/_search`

Yet the Wazuh app always returns the same three errors cited above in Kibana.

**Comment by hcv-target** [comment]
Perhaps also of use in diagnosing this is this log trace from /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log, after restarting and two attempted loads of the wazuh app:

> {"date":"2019-10-03T16:02:14.665Z","level":"error","location":"initialize:init","message":"Authorization Exception"}
{"date":"2019-10-03T16:02:14.665Z","level":"error","location":"initialize:checkKibanaStatus","message":"Authorization Exception"}
{"date":"2019-10-03T16:02:14.681Z","level":"error","location":"initialize:saveConfiguration","message":"[security_exception] action [indices:admin/create] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:02:14.694Z","level":"error","location":"monitoring:getConfig","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:02:14.760Z","level":"error","location":"monitoring:saveStatus","message":"Could not check if the index wazuh-monitoring-3.x-2019.10.03 exists due to Authorization Exception"}
{"date":"2019-10-03T16:02:14.874Z","level":"info","location":"initialize","message":"App ready to be used."}
{"date":"2019-10-03T16:04:35.748Z","level":"error","location":"wazuh-api-elastic:getAPIEntries","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:04:35.778Z","level":"error","location":"wazuh-api-elastic:getAPIEntries","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:04:35.890Z","level":"error","location":"wazuh-api-elastic:getAPIEntries","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:04:36.166Z","level":"error","location":"wazuh-api-elastic:getAPIEntries","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:04:36.242Z","level":"error","location":"wazuh-elastic:getSetupInfo","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:10:09.862Z","level":"error","location":"wazuh-api-elastic:getAPIEntries","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:10:09.886Z","level":"error","location":"wazuh-api-elastic:getAPIEntries","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:10:10.008Z","level":"error","location":"wazuh-api-elastic:getAPIEntries","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:10:10.394Z","level":"error","location":"wazuh-api-elastic:getAPIEntries","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}
{"date":"2019-10-03T16:10:10.437Z","level":"error","location":"wazuh-elastic:getSetupInfo","message":"[security_exception] action [indices:data/read/search] is unauthorized for user [kibana]"}

Thanks for any additional light you can shed, @jsanchez91 and @adri9valle !

**Comment by adri9valle** [comment]
Hi @hcv-target 

Sorry for the late response.

> After successfully enabling TLS for transport and server in kibana, elastic, metricbeat and filebeat, which all work perfectly, launching wazuh-app now returns three errors when opening the app

For this, I guess that you enabled XPACK for that. I see this error: `action [indices:admin/create] is unauthorized for user [kibana]"`, that's why the internal request to get the API entries from the `.wazuh` index is done by the Kibana user who has not permissions since the XPACK was enabled.

In the `kibana.yml` you can edit the username that Kibana uses and his password, please try to configure the `elastic` user instead `kibana`:

**kibana.yml**
```
...
...
xpack.security.enabled: true
elasticsearch.username: "elastic"
elasticsearch.password: "<your_elastic_password>"
...
...
```

After that, restart Kibana and login again but with the elastic user and let me know if this works for you, otherwise, I'll appreciate you send us the last lines of the `/usr/share/kibana/optimize/wazuh-logs/wazuhapp-plain.log`. I hope it helps.

Regards,

**Comment by hcv-target** [comment]
@adri9valle , THANKS!!!, that was the piece I needed. This solved the immediate problem, which led me to find that logstash wasn't running, and so had to set up the users and roles needed for the wazhuh indices.

@ips972 , if you're still having problems after taking the above advice into consideration, I'd be happy to share the steps I had to take to configure logstash.

**Comment by adri9valle** [comment]
Hi @hcv-target,

I'm glad to know that it works for you!

Due to the problem is solved I go to close this issue. If you have other problems or doubts, don't hesitate to open a new issue we're here to help!

@ips972 please, try the steps that @hcv-target tried, if your problem still persists don't hesitate to re-open this issue.

Regards,
