### ISSUE TITLE
Wazuh API password stored unencrypted in Elasticsearch

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh-kibana-app#324]
Greetings!

While trying to change the default Wazuh API password, I find out that the Wazuh Kibana Application configuration is accessible by doing a simple Elasticsearch query:
```bash
curl -s -XGET http://elasticsearch:9200/.wazuh/wazuh-configuration/_search
```

The result of that query is:
```json
{
    "took": 0,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 1.0,
        "hits": [
            {
                "_index": ".wazuh",
                "_type": "wazuh-configuration",
                "_id": "1513629884013",
                "_score": 1.0,
                "_source": {
                    "api_user": "foo",
                    "api_password": "YmFy",
                    "url": "https://wazuh",
                    "api_port": "55000",
                    "insecure": "true",
                    "component": "API",
                    "cluster_info": {
                        "manager": "wazuh-manager",
                        "cluster": "Disabled",
                        "status": "disabled"
                    },
                    "extensions": {
                        "oscap": true,
                        "audit": true,
                        "pci": true
                    }
                }
            }
        ]
    }
}
```

From there, you only need `base64` and you have the Wazuh API password in clear text:
```bash
$ echo "YmFy" | base64 -D
bar
```

Or, you can use the DevTools in Kibana:
![screen shot 2018-03-19 at 17 36 05](https://user-images.githubusercontent.com/3448802/37623749-230c68ac-2b9c-11e8-9a47-d121e318856e.png)

From [the source code](https://github.com/wazuh/wazuh-kibana-app/blob/master/server/api/wazuh-elastic.js#L26), I can see that it's currently your way of storing and accessing the Wazuh API password.

Would it be possible to store the Wazuh API password somewhere else? 😄 

My problem with that is the fact that password is highly sensitive and the number of people that can have access to it should be extremely limited, while the Elasticsearch API could be opened to a larger number of people.

Thanks a lot for your help!

**Comment by JuanjiJG** [comment]
Hello @JPLachance,

Thanks for your valuable feedback!

We need to use Elasticsearch to store the API credentials, we create Elasticsearch indices that act like databases for the Wazuh app. The API password is always present on the backend, that means, the Kibana server, not on the app frontend.

If you need an extra security layer, you can try X-Pack, a plugin made by the Elastic team, which provides SSL encryption and role-based access control, providing capabilities to define users and their specific access roles. You can read more information here: https://www.elastic.co/products/x-pack

If you set up X-Pack, you'll define a password, and nobody will be able to make queries to Elasticsearch to get the API password.

If you still have more questions, please let me know!

Bets regards,
Juanjo

**Comment by JPLachance** [comment]
Hi @JuanjiJG,

Thanks for your fast reply!

We are using X-Pack so it look's like we are going to be fine.

One question: what role should I define for the Wazuh Kibana application in Elasticsearch? I found an issue that is still opened on that subject: https://github.com/wazuh/wazuh/issues/134#issuecomment-303694223

Thanks 😃

**Comment by jesusgn90** [comment]
Hello @JPLachance currently we are researching the perfect role to be used in order to deploy Kibana plus the Wazuh App on the right way. It's important to keep in mind that the Wazuh App is an embedded plugin for Kibana. From this point, here is a summary of the main points here:

- While you are using X-Pack you have at least two kinds of user:

1. The user who starts the Kibana process, it means the user who is written under `/etc/kibana/kibana.yml` file as `elasticsearch.username` and `elasticsearch.password` and it's used by Kibana to fetch data from Elastic. Since it loads the Wazuh App along few more plugins such as `monitoring` it needs to be a `superuser`, it means you should use the `elastic` user who is able to fetch any index with high privileges. 
2. The user who uses the Kibana UI. This user could be the `elastic` user itself or maybe another user. If you have a fresh wazuh app installation your user role should give privileges to at least the following things, maybe something more(currently researching):

__Currently:__

```
- .kibana* --> read,write
- .wazuh --> read,write
- .wazuh-version --> read,write
- .wazuh-alerts* --> read
- .wazuh-monitoring* --> read,write
```
__on next packages (don't know exact date):__

```
- .kibana* --> read
- .wazuh --> read
- .wazuh-version --> read
- .wazuh-alerts* --> read
- .wazuh-monitoring* --> read

Also you will be able to limit more in deep the data for  your users than just now.
```

With the above privileges the very first time you enter the Wazuh App it will advice you from the x-pack license and when you click on `dismiss` it shows a not harmful error because it stores your click on dismiss but you have not permissions.

On the other hand, we are going to release a new package soon (maybe will be more packages before) which modifies the way we fetch data from the backend, modifies the way the authenticated user access the data, etc. That "git" branch is unstable so we cannot publish it yet. Any case, with your current package my suggestion is to start Kibana with the `elastic` user and log in with the `elastic` user too, when done let's create a role (i.e: wazuh-user) and try the above privileges, create a user (i.e: john) and assign him the wazuh-user role. 

As I said, we are going to publish a package soon with a better handling of these kind of things and it will be along an updated documentation documents within our installation guide where we will explain all about this scenario. Just now, you should manage your environment as I described above.

Best regards,
Jesús

**Comment by JPLachance** [comment]
Hi @jesusgn90,

Thanks for your answer.

After exploring your source code, I came out with the following Puppet definition for my Elasticsearch role:
```
elasticsearch::role { 'wazuh_kibana':
  privileges => {
    'cluster' => ['manage_index_templates', 'monitor'],
    'indices' => [
      {
        'names'      => ['.kibana*', '.reporting-*'],
        'privileges' => ['all']
      },
      {
        'names'      => '.monitoring-*',
        'privileges' => ['read', 'read_cross_cluster']
      },
      {
        'names'      => ['.old-wazuh', '.wazuh', '.wazuh-version', 'wazuh-*'],
        'privileges' => ['all']
      }
    ]
  }
}
```

This role gives the same access rights that are given in the `kibana_system` role that comes out of the box with X-Pack. To Kibana required privileges, I added the full access to the following indices:
- `.old-wazuh` => Because you may use that between major versions
-  `.wazuh`
- `.wazuh-version'`
- `wazuh-*` => Should cover all the needs of your plugin

For now, I'm giving too much access rights, but it finally works. The official documentation will certainly help a lot here in the future!

Thanks for your time 😃

**Comment by jesusgn90** [comment]
Hi @JPLachance I forgot you created this issue too, it's really great your work this days! Yes, that role could be enough for a standard installation. For now and for the backend we need a slightly different role, since we are modifying our backend code on a breaking way to our current code. On next packages we are no longer using calls to Elasticsearch using the incoming request, only the internal user, by the way your role will be fine for the UI user! 

Also we are going to limit from the backend the access to certain index patterns depending on the user role. Additionally we are going to build/store the visualizations data _on the fly_ depending on the current user. On next packages the whole conversation will be solved and regarding to the issue title (clear password) I think it's enough with the above description and with the fix commented on the other issues, thanks one more time. 

Don't hesitate to open a new issue if you need anything.

King regards,
Jesús

**Comment by sonofagl1tch** [comment]
Hi! looks like i opened an issue similar to this over at https://github.com/wazuh/wazuh/issues/696. 

I am trying to programmatically populate the following fields in the .wazuh index so that I can use a cloudformation template to build out a wazuh server and attach clients to it.

> "api_user":
 "foo",
"api_password": "YmFy",
 "url": "https://wazuh",
  "api_port": "55000",

do you have a reference document or go to method for this?

also apologies if i hijacked the thread and have no issues moving this question back to the other issue I opened if it does not relate to this open issue closely enough. thanks!

**Comment by JPLachance** [comment]
Greetings!

On my side, I use the [wazuh-kibana](https://hub.docker.com/r/wazuh/wazuh-kibana/) Docker image to run the wazuh-kibana-application. In the source code repository of that image, there is a script called [entrypoint.sh](https://github.com/wazuh/wazuh-docker/blob/master/kibana/config/entrypoint.sh) that is setting up the credentials for the Wazuh API in an object in Elasticsearch.

To make that work with X-Pack, I simply modified an old version of their script:
```bash
#!/usr/bin/env bash
# Wazuh App Copyright (C) 2018 Wazuh Inc. (License GPLv2)

set -e

cmd="kibana"

API_PROTOCOL=${API_PROTOCOL:-https}
API_SERVER=${API_SERVER:-wazuh}
API_PORT=${API_PORT:-55000}
API_USER=${API_USER:-foo}
API_PASS=${API_PASS:-bar}

ES_URL=${ES_URL:-'http://elasticsearch:9200'}
ES_USER=${ES_USER:-kibana}
ES_PASSWORD=${ES_PASSWORD:-changeme}

if [ ! -d /usr/share/kibana/config/certificate ]; then
  echo "Generating SSL certificates"

  mkdir -p /usr/share/kibana/config/certificate

  openssl req -x509 -batch -nodes -days 365 -newkey rsa:2048 -keyout /usr/share/kibana/config/certificate/kibana-cert.key -out /usr/share/kibana/config/certificate/kibana-cert.pem >/dev/null
else
  echo "SSL certificates already present"
fi

until curl -u ${ES_USER}:${ES_PASSWORD} -XGET "${ES_URL}"; do
  >&2 echo "Elastic is unavailable - sleeping for 5 seconds"

  sleep 5
done

>&2 echo "Elastic is up - executing commands"

sleep 5

echo "Inserting default alerts templates"
cat /usr/share/kibana/config/wazuh-elastic6-template-alerts.json | curl -u ${ES_USER}:${ES_PASSWORD} -XPUT "${ES_URL}/_template/wazuh" -H 'Content-Type: application/json' -H "Accept: application/json" -d @-

sleep 5

echo -e "\nInserting default monitoring templates"
cat /usr/share/kibana/config/wazuh-elastic6-template-monitoring.json | curl -u ${ES_USER}:${ES_PASSWORD} -XPUT "${ES_URL}/_template/wazuh-agent" -H 'Content-Type: application/json' -H "Accept: application/json" -d @-

sleep 5

echo -e "\nInserting sample alert"
cat /usr/share/kibana/config/alert_sample.json | curl -u ${ES_USER}:${ES_PASSWORD} -XPUT "${ES_URL}/wazuh-alerts-3.x-"`date +%Y.%W`"/wazuh/sample" -H 'Content-Type: application/json' -H "Accept: application/json" -d @-

sleep 5

echo -e "\nSetting Wazuh API credentials into the Wazuh Kibana application"

API_PASS_BASE64=$(echo -n ${API_PASS} | base64)

# The Wazuh Kibana application configuration is the document with the ID 1513629884013, don't change that!
curl -s -u ${ES_USER}:${ES_PASSWORD} -XPOST "${ES_URL}/.wazuh/wazuh-configuration/1513629884013" -H 'Content-Type: application/json' -H "Accept: application/json" -d'
{
    "api_user": "'${API_USER}'",
    "api_password": "'${API_PASS_BASE64}'",
    "url": "'${API_PROTOCOL}'://'${API_SERVER}'",
    "api_port": "'${API_PORT}'",
    "insecure": "true",
    "component": "API",
    "active": true,
    "extensions": {
        "oscap": true,
        "audit": true,
        "pci": true
    },
    "cluster_info": {
        "node": "wazuh-manager-master",
        "cluster": "wazuh",
        "manager": "wazuh-manager-master-0",
        "status": "enabled"
    }
}
'

sleep 5

echo -e "\nStarting Kibana..."

exec ${cmd}
```

I hope this helps! 😄 

Best regards,
Jean-Philippe Lachance

**Comment by sonofagl1tch** [comment]
It looks ike this curl POST command added the information to the index however it isnt populating in the UI. This means that I am unable to check on what agents are connected or use the wazuh dashboards. Is there anything I can add to the POST to fix this?

`[ec2-user@ip-172-16-0-21 ~]$ curl -s -XGET http://localhost:9200/.wazuh/wazuh-configuration/_search {"took":0,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":".wazuh","_type":"wazuh-configuration","_id":"uFJFtmMBIEqpmXP63aM6","_score":1.0,"_source": {"took":0,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":".wazuh","_type":"wazuh-configuration","_score":1.0,"_source":{"api_user":"wazuh","api_password":"d2F6dWg=","url":"http://172.16.0.21","api_port":"55000","insecure":"true","component":"API","cluster_info":{"manager":"ip-172-16-0-21.ec2.internal","cluster":"Disabled","status":"disabled"},"extensions":{"audit":true,"pci":true,"oscap":true,"aws":false,"virustotal":false}}}]}}}]}}`

<img width="1438" alt="screen shot 2018-05-31 at 9 22 31 am" src="https://user-images.githubusercontent.com/20155474/40785815-84c654fa-64b7-11e8-9a23-abab29502765.png">

**Comment by sonofagl1tch** [comment]
@JPLachance I found that running your script verbatim fixed the UI issue I was having but introduced new issues (as expected). I am going to do an iterative approach to modifying your script to work for me. I will post a working script hopefully soon. thanks!

**Comment by sonofagl1tch** [comment]
the following code looks to implement the feature I am looking for. Thank you very much for your help!

```API_PROTOCOL=${API_PROTOCOL:-http}
API_SERVER=${API_SERVER:-172.16.0.21}
API_PORT=${API_PORT:-55000}
API_USER=${API_USER:-wazuh}
API_PASS=${API_PASS:-wazuh}
API_PASS_BASE64=$(echo -n ${API_PASS} | base64)
ES_URL=${ES_URL:-'http://localhost:9200'}
ES_USER=${ES_USER:-kibana}
ES_PASSWORD=${ES_PASSWORD:-changeme}
until curl -u ${ES_USER}:${ES_PASSWORD} -XGET "${ES_URL}"; do
  >&2 echo "Elastic is unavailable - sleeping for 5 seconds"
  sleep 5
done
>&2 echo "Elastic is up - executing commands"
sleep 5
echo -e "\nSetting Wazuh API credentials into the Wazuh Kibana application"
# The Wazuh Kibana application configuration is the document with the ID 1513629884013, don't change that!
curl -s -u ${ES_USER}:${ES_PASSWORD} -XPOST "${ES_URL}/.wazuh/wazuh-configuration/1513629884013" -H 'Content-Type: application/json' -H "Accept: application/json" -d'
{
    "api_user": "'${API_USER}'",
    "api_password": "'${API_PASS_BASE64}'",
    "url": "'${API_PROTOCOL}'://'${API_SERVER}'",
    "api_port": "'${API_PORT}'",
    "insecure": "true",
    "component": "API",
    "active": true,
    "extensions": {
        "oscap": true,
        "audit": true,
        "pci": true
    },
    "cluster_info": {
        "node": "wazuh-manager-master",
        "cluster": "wazuh",
        "manager": "wazuh-manager-master-0",
        "status": "enabled"
    }
}
'

**Comment by jesusgn90** [comment]
@sonofagl1tch from my view and from the comments under https://github.com/wazuh/wazuh/issues/696 and this issue itself I understand your problem is on the good way and both issues are closed, any case, You still need help?

Regards,
Jesús

**Comment by JuanjiJG** [comment]
Hello @JPLachance,

If you don't want to use X-Pack, you can also try [SearchGuard](https://search-guard.com/). It's an Elasticsearch plugin that allows you to provide security to your ELK instance, and they provide both community and enterprise versions.

At the moment we provide support for X-Pack's _Security_ plugin. You can read our configuration guide [here](https://documentation.wazuh.com/current/user-manual/kibana-app/configure-xpack/index.html). Maybe in the future will provide steps to configure SearchGuard, but there's no estimated ETA at the moment.

Let us know if you have more questions. In the future, it's okay to open a new issue and reference to an older one if this is quite outdated, so you can have your question on the top of the list, and this way the conversation won't get too long.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Hi @JPLachance ,

In addition I want to say that we are planning to release a full RBAC system for Wazuh which means you won't need to store credentials any more. Also you will use roles for users which brings you a full security system, that's why we are not developing more features focused on X-Pack security. 

On the other hand, Elasticsearch will remain open unless you close it for customers, so even using our RBAC system you will have to secure your Elasticsearch nodes using some extension such as X-Pack, SearchGuard, NGINX login, etc.

Take a look into https://github.com/wazuh/wazuh-api/issues/114 for details.

Regards!

**Comment by JPLachance** [comment]
Hello!

I looked at your X-Pack documentation and at your RBAC feature, it looks promising! I still have some questions though. 😇 

@jesusgn90, when you say "you won't need to store credentials anymore", what do you mean? Like @JuanjiJG explained, "We need to use Elasticsearch to store the API credentials, we create Elasticsearch indices that act like databases for the Wazuh app."

I think that even with RBAC, the Wazuh Kibana application will need credentials to speak with the Wazuh API. The place where those credentials are stored will probably still be Elasticsearch.

This brings me to the X-Pack setup documentation. In the [wazuh-standard-user](https://documentation.wazuh.com/current/user-manual/kibana-app/configure-xpack/defining-xpack-users.html#wazuh-standard-user) documentation, you suggest to grant the wazuh-basic role to basic users and the wazuh-basic role have read access to the `.wazuh` index. If the Wazuh API credentials are still stored in that index, well... 😄 The `GET .wazuh/wazuh-configuration/1513629884013` query will return you the API credentials. Do the wazuh-basic role really need access to the `.wazuh` index?

A solution would be to store the API credentials in an index for which only the Kibana backend server have access to and for which the frontend don't have access. For example, we would create the ` .wazuh-app-backend/wazuh-configuration/1513629884013` document and grant access to that document only to the backend application itself.

  Basically, only the `wazuhsystem` user (name taken from [your documentation](https://documentation.wazuh.com/current/user-manual/kibana-app/configure-xpack/configure-xpack-users.html)) should have access to the API credentials. A user browsing Kibana and the Wazuh Kibana application should never be able to get the Wazuh API credentials.

  Does it make sens?

Again, thanks for your time and support!
